apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-pod-identity-sa
  namespace: default
  annotations:
    custom-pod-identity/policy-document: '{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Action": "sts:AssumeRole", "Resource": "*"}]}'
    custom-pod-identity/service-name: "test-service"
